//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResourcesModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResourcesModel() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Model.Resources.Localization.AppResourcesModel", typeof(AppResourcesModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The character {0} cannot equip the weapon {1}.
        /// </summary>
        internal static string CantEquipWeaponItemFormat {
            get {
                return ResourceManager.GetString("CantEquipWeaponItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health is critically low with only {0} health points remaining!.
        /// </summary>
        internal static string CharacterCriticalHealth {
            get {
                return ResourceManager.GetString("CharacterCriticalHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Here is information about the character {0}. {1} {2} {3}.
        /// </summary>
        internal static string CharacterDescriptionFormat {
            get {
                return ResourceManager.GetString("CharacterDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à They are holding a {0}, which can deal {1} damage.
        /// </summary>
        internal static string CharacterEquippedWeapon {
            get {
                return ResourceManager.GetString("CharacterEquippedWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} health points remaining.
        /// </summary>
        internal static string CharacterHealthStatus {
            get {
                return ResourceManager.GetString("CharacterHealthStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Their inventory is empty.
        /// </summary>
        internal static string CharacterInventoryEmpty {
            get {
                return ResourceManager.GetString("CharacterInventoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à They have the following items in their inventory: {0}.
        /// </summary>
        internal static string CharacterInventoryItems {
            get {
                return ResourceManager.GetString("CharacterInventoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à They are not carrying any weapon and will deal {0} base damage.
        /// </summary>
        internal static string CharacterNoWeapon {
            get {
                return ResourceManager.GetString("CharacterNoWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is a consumable item called {0}, which restores {1} health points.
        /// </summary>
        internal static string ConsumableItemDescription {
            get {
                return ResourceManager.GetString("ConsumableItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fr-FR.
        /// </summary>
        internal static string CultureInfo {
            get {
                return ResourceManager.GetString("CultureInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The character {0} equipped the weapon {1}.
        /// </summary>
        internal static string EquippedWeaponItemFormat {
            get {
                return ResourceManager.GetString("EquippedWeaponItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : file couldn&apos;t be serialized. Message :.
        /// </summary>
        internal static string FileServiceManager_ExportStoryAsync_JsonException {
            get {
                return ResourceManager.GetString("FileServiceManager_ExportStoryAsync_JsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid story data in the file..
        /// </summary>
        internal static string FileServiceManager_ImportStoryAsync_ImportedStoryException {
            get {
                return ResourceManager.GetString("FileServiceManager_ImportStoryAsync_ImportedStoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The file does not contain a valid story. Message :.
        /// </summary>
        internal static string FileServiceManager_ImportStoryAsync_JsonException {
            get {
                return ResourceManager.GetString("FileServiceManager_ImportStoryAsync_JsonException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TextToSpeech rate setting value must a float between 0.5 and 2.0..
        /// </summary>
        internal static string GlobalSettings_VoicRateTTS_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("GlobalSettings_VoicRateTTS_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TextToSpeech volume setting value must be between 0 and 100..
        /// </summary>
        internal static string GlobalSettings_VolumeTTS_ArgumentOutOfRangeException {
            get {
                return ResourceManager.GetString("GlobalSettings_VolumeTTS_ArgumentOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is a key item called {0}. It is used to unlock certain paths.
        /// </summary>
        internal static string KeyItemDescription {
            get {
                return ResourceManager.GetString("KeyItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The KeyItem to be added cannot be null.
        /// </summary>
        internal static string Option_AddKeyItem_ArgumentNullException {
            get {
                return ResourceManager.GetString("Option_AddKeyItem_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The word to be added cannot be empty..
        /// </summary>
        internal static string Option_AddWordInList_ArgumentException {
            get {
                return ResourceManager.GetString("Option_AddWordInList_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The KeyItem to be removed cannot be null.
        /// </summary>
        internal static string Option_RemoveKeyItem_ArgumentNullException {
            get {
                return ResourceManager.GetString("Option_RemoveKeyItem_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The word to be removed cannot be empty..
        /// </summary>
        internal static string Option_RemoveWordInList_ArgumentException {
            get {
                return ResourceManager.GetString("Option_RemoveWordInList_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : The event must belong to the story&apos;s events. Message : .
        /// </summary>
        internal static string Story_SetFirstEvent_InvalidOperationException {
            get {
                return ResourceManager.GetString("Story_SetFirstEvent_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The voiceRate parameter must be between {0} and {1}..
        /// </summary>
        internal static string TTS_SetVoiceRate_Exception {
            get {
                return ResourceManager.GetString("TTS_SetVoiceRate_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice {0} has not been found..
        /// </summary>
        internal static string TTS_SetVoiceType_Exception {
            get {
                return ResourceManager.GetString("TTS_SetVoiceType_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to set the voice: {0}. Message : .
        /// </summary>
        internal static string TTS_SetVoiceType_NotFound {
            get {
                return ResourceManager.GetString("TTS_SetVoiceType_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The voiceVolume parameter must be between {0} and {1}..
        /// </summary>
        internal static string TTS_SetVoiceVolume_Exception {
            get {
                return ResourceManager.GetString("TTS_SetVoiceVolume_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The character {0} unequipped the weapon {1}.
        /// </summary>
        internal static string UnEquippedWeaponItemFormat {
            get {
                return ResourceManager.GetString("UnEquippedWeaponItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The character {0} has been healed for {1} HP using {2}.
        /// </summary>
        internal static string UsedConsumableItemFormat {
            get {
                return ResourceManager.GetString("UsedConsumableItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The character {0} used {1}.
        /// </summary>
        internal static string UsedKeyItemFormat {
            get {
                return ResourceManager.GetString("UsedKeyItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is a weapon called {0}, which deals {1} damage when equipped.
        /// </summary>
        internal static string WeaponItemDescription {
            get {
                return ResourceManager.GetString("WeaponItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error initializing speech recognition : .
        /// </summary>
        internal static string WindowsRecognition_Constructor_Exception {
            get {
                return ResourceManager.GetString("WindowsRecognition_Constructor_Exception", resourceCulture);
            }
        }
    }
}
