//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("View.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add Option.
        /// </summary>
        internal static string AddOption {
            get {
                return ResourceManager.GetString("AddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add word.
        /// </summary>
        internal static string AddWord {
            get {
                return ResourceManager.GetString("AddWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new event.
        /// </summary>
        internal static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new story.
        /// </summary>
        internal static string CreateNewStory {
            get {
                return ResourceManager.GetString("CreateNewStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete &quot;{0}&quot;.
        /// </summary>
        internal static string DeleteConfirmationFormat {
            get {
                return ResourceManager.GetString("DeleteConfirmationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this option ?.
        /// </summary>
        internal static string DeleteOptionConfirmationText {
            get {
                return ResourceManager.GetString("DeleteOptionConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete this story?.
        /// </summary>
        internal static string DeleteStoryConfirmation {
            get {
                return ResourceManager.GetString("DeleteStoryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Successfully deleted &quot;{0}&quot;.
        /// </summary>
        internal static string DeleteSuccessFormat {
            get {
                return ResourceManager.GetString("DeleteSuccessFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have unsaved changes. If you go back, these changes will be lost. Do you want to continue?.
        /// </summary>
        internal static string DiscardChangesMessage {
            get {
                return ResourceManager.GetString("DiscardChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editor.
        /// </summary>
        internal static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The word cannot be empty..
        /// </summary>
        internal static string ErrorEmptyWord {
            get {
                return ResourceManager.GetString("ErrorEmptyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter both a title and description for the event..
        /// </summary>
        internal static string ErrorEventTitleDesc {
            get {
                return ResourceManager.GetString("ErrorEventTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option title cannot be empty.
        /// </summary>
        internal static string ErrorOptionTitle {
            get {
                return ResourceManager.GetString("ErrorOptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter both a title and description for the option..
        /// </summary>
        internal static string ErrorOptionTitleDesc {
            get {
                return ResourceManager.GetString("ErrorOptionTitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Event Title.
        /// </summary>
        internal static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story exported successfully.
        /// </summary>
        internal static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to your story list.
        /// </summary>
        internal static string GoToStoryList {
            get {
                return ResourceManager.GetString("GoToStoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import a story.
        /// </summary>
        internal static string ImportStory {
            get {
                return ResourceManager.GetString("ImportStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story imported successfully.
        /// </summary>
        internal static string ImportSuccess {
            get {
                return ResourceManager.GetString("ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Linked event.
        /// </summary>
        internal static string LinkedEventOption {
            get {
                return ResourceManager.GetString("LinkedEventOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have three buttons : Play, Create and settings.
        /// </summary>
        internal static string MainPageDescription {
            get {
                return ResourceManager.GetString("MainPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New game.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add description.
        /// </summary>
        internal static string NewStoryDescPlaceholder {
            get {
                return ResourceManager.GetString("NewStoryDescPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Story.
        /// </summary>
        internal static string NewStoryPlaceholder {
            get {
                return ResourceManager.GetString("NewStoryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No words added yet..
        /// </summary>
        internal static string NoWordsAdded {
            get {
                return ResourceManager.GetString("NoWordsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the name of the option.
        /// </summary>
        internal static string OptionNameInputText {
            get {
                return ResourceManager.GetString("OptionNameInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option name.
        /// </summary>
        internal static string OptionNameTitle {
            get {
                return ResourceManager.GetString("OptionNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select an event.
        /// </summary>
        internal static string OptionPageEvents {
            get {
                return ResourceManager.GetString("OptionPageEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create/Edit Option.
        /// </summary>
        internal static string OptionTitle {
            get {
                return ResourceManager.GetString("OptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter event title.
        /// </summary>
        internal static string PlaceholderEventTitle {
            get {
                return ResourceManager.GetString("PlaceholderEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter option text.
        /// </summary>
        internal static string PlaceholderOptionText {
            get {
                return ResourceManager.GetString("PlaceholderOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter story content.
        /// </summary>
        internal static string PlaceholderStoryContent {
            get {
                return ResourceManager.GetString("PlaceholderStoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This will restart the app.
        /// </summary>
        internal static string RestartWarning {
            get {
                return ResourceManager.GetString("RestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à How to play :
        ///
        ///Listen to what the story is saying and say out loud your choice from the options given.
        /// </summary>
        internal static string RulesPlayer {
            get {
                return ResourceManager.GetString("RulesPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The story has been saved successfully..
        /// </summary>
        internal static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select your language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story Content.
        /// </summary>
        internal static string StoryContent {
            get {
                return ResourceManager.GetString("StoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The name of your story contains unauthorized characters.
        /// </summary>
        internal static string StoryNameInvalidErrorDesc {
            get {
                return ResourceManager.GetString("StoryNameInvalidErrorDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story Invalid.
        /// </summary>
        internal static string StoryNameInvalidErrorTitle {
            get {
                return ResourceManager.GetString("StoryNameInvalidErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option text.
        /// </summary>
        internal static string TextWordOption {
            get {
                return ResourceManager.GetString("TextWordOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter the words linked to the option.
        /// </summary>
        internal static string TextWordOptionInput {
            get {
                return ResourceManager.GetString("TextWordOptionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à AudioRPG.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create an Event.
        /// </summary>
        internal static string TitleCreateEvent {
            get {
                return ResourceManager.GetString("TitleCreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story List.
        /// </summary>
        internal static string TitleStoryList {
            get {
                return ResourceManager.GetString("TitleStoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Story Map.
        /// </summary>
        internal static string TitleStoryMap {
            get {
                return ResourceManager.GetString("TitleStoryMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Stories.
        /// </summary>
        internal static string TitleYourStory {
            get {
                return ResourceManager.GetString("TitleYourStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change theme.
        /// </summary>
        internal static string ToggleTheme {
            get {
                return ResourceManager.GetString("ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have unsaved changes. Do you want to save your changes before proceeding?.
        /// </summary>
        internal static string UnsavedChangesMessage {
            get {
                return ResourceManager.GetString("UnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice Speed.
        /// </summary>
        internal static string VoiceSpeed {
            get {
                return ResourceManager.GetString("VoiceSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voice Volume.
        /// </summary>
        internal static string VoiceVolume {
            get {
                return ResourceManager.GetString("VoiceVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the Creator Area.
        /// </summary>
        internal static string WelcomeCreator {
            get {
                return ResourceManager.GetString("WelcomeCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to AudioRPG.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This word already exists in the list.
        /// </summary>
        internal static string WordAlreadyExists {
            get {
                return ResourceManager.GetString("WordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
